/**
 * The document fixture set for scenario 3, with ground truth.
 *
 * Single source of truth, imported by BOTH prisma/seed.ts and the eval harness.
 * If these lived in the seed alone, the evals would be asserting against numbers
 * copied by hand — and the first time someone edited one and not the other, the
 * harness would start passing for the wrong reason.
 *
 * The page images themselves are generated by scripts/generate-fixtures.ps1; the
 * expected values below must match what that script prints.
 *
 * Note the `issuer` / `counterparty` split. Which organisation sits on which side
 * depends on who raised the document: a contractor issues an invoice TO the
 * awarding body, but the awarding body issues a letter of award BACK to the
 * contractor. Two of the five fixtures below are buyer-issued for exactly that
 * reason — an extractor that assumes the prominent name at the top is always the
 * counterparty gets them backwards, and reconciliation that assumes a fixed
 * arrangement flags valid documents as mismatches.
 */

export type FixtureKind =
  | "INVOICE"
  | "PURCHASE_ORDER"
  | "PROGRESS_CLAIM"
  | "LETTER_OF_AWARD";

export interface DocumentFixture {
  applicationReference: string;
  kind: FixtureKind;
  label: string;
  assetPath: string;
  /** True for the fixture whose figures deliberately disagree with the CRM. */
  isDeliberateMismatch: boolean;
  /** What a correct extraction returns. Asserted by the eval harness. */
  groundTruth: {
    documentNumber: string;
    /** Normalised YYYY-MM-DD. */
    documentDate: string;
    /** Digits and decimal point only, as the schema requires. */
    totalAmount: string;
    /** Whose document it is — the letterhead. */
    issuer: string;
    /** The other organisation named on the page. */
    counterparty: string;
    /** Empty when the page prints no reference separate from its own number. */
    contractReference: string;
  };
  /** The verdict reconciliation must reach on a correct extraction. */
  expectedVerdict: "ANOMALY_FREE" | "MISMATCH_FLAGGED";
}

export const DOCUMENT_FIXTURES: DocumentFixture[] = [
  {
    // Contractor-issued. The worked example printed on slide 8 of the brief.
    applicationReference: "APP-2026-0301",
    kind: "PROGRESS_CLAIM",
    label: "Contract progress claim #1024 — the worked example from slide 8",
    assetPath: "/fixtures/progress-claim-1024.png",
    isDeliberateMismatch: false,
    groundTruth: {
      documentNumber: "1024",
      documentDate: "2024-10-25",
      totalAmount: "50000.00",
      issuer: "BINA HARMONI SDN BHD",
      counterparty: "ACME CORP",
      contractReference: "AC/2024/1024",
    },
    expectedVerdict: "ANOMALY_FREE",
  },
  {
    // Contractor-issued.
    applicationReference: "APP-2026-0498",
    kind: "INVOICE",
    label: "Invoice INV-8871 — M&E works, JKR Selangor",
    assetPath: "/fixtures/invoice-8871.png",
    isDeliberateMismatch: false,
    groundTruth: {
      documentNumber: "INV-8871",
      documentDate: "2026-03-12",
      totalAmount: "486300.00",
      issuer: "TEGAS ELEKTRIK SDN BHD",
      counterparty: "Jabatan Kerja Raya Selangor",
      contractReference: "JKR/S/2025/118-ME",
    },
    expectedVerdict: "ANOMALY_FREE",
  },
  {
    // Contractor-issued, degraded scan, and THE DELIBERATE MISMATCH: the
    // certified claim reads 742,500.00 while the application declares
    // 724,500.00 — a digit transposition.
    applicationReference: "APP-2026-0517",
    kind: "PROGRESS_CLAIM",
    label: "Certified progress claim PC-3302 (scanned) — MRT Corp package 44",
    assetPath: "/fixtures/progress-claim-3302-scan.png",
    isDeliberateMismatch: true,
    groundTruth: {
      documentNumber: "PC-3302",
      documentDate: "2026-02-28",
      totalAmount: "742500.00",
      issuer: "TEGAS ELEKTRIK SDN BHD",
      counterparty: "MRT Corp Sdn Bhd",
      contractReference: "MRTC/PKG/2025/44",
    },
    expectedVerdict: "MISMATCH_FLAGGED",
  },
  {
    // BUYER-issued: TNB raised this order, so Planworth's client is the
    // counterparty, not the issuer.
    applicationReference: "APP-2026-0455",
    kind: "PURCHASE_ORDER",
    label: "Purchase order TNB/PO/2026/44127",
    assetPath: "/fixtures/purchase-order-44127.png",
    isDeliberateMismatch: false,
    groundTruth: {
      documentNumber: "TNB/PO/2026/44127",
      documentDate: "2026-01-06",
      totalAmount: "1250000.00",
      issuer: "TENAGA NASIONAL BERHAD",
      counterparty: "Perdana Supply Chain Sdn Bhd",
      contractReference: "",
    },
    expectedVerdict: "ANOMALY_FREE",
  },
  {
    // AWARDING-BODY-issued: JKR raised this letter, so the client is again the
    // counterparty.
    applicationReference: "APP-2026-0412",
    kind: "LETTER_OF_AWARD",
    label: "Letter of award JKR/S/2025/118",
    assetPath: "/fixtures/letter-of-award-118.png",
    isDeliberateMismatch: false,
    groundTruth: {
      documentNumber: "JKR/S/2025/118",
      documentDate: "2025-11-19",
      totalAmount: "3480000.00",
      issuer: "JABATAN KERJA RAYA SELANGOR",
      counterparty: "Bina Harmoni Sdn Bhd",
      contractReference: "",
    },
    expectedVerdict: "ANOMALY_FREE",
  },
];
